apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: REDIS_URL
              value: {{ .Values.backend.env.REDIS_URL | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.backend.env.CORS_ORIGINS | quote }}
            - name: AUTH_REQUIRED
              value: {{ .Values.backend.env.AUTH_REQUIRED | quote }}
          resources:
{{ toYaml .Values.resources.backend | indent 12 }}
